-- MySQL Script generated by MySQL Workbench
-- Mon Nov  1 12:59:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Service` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
-- -----------------------------------------------------
-- Schema HelpU
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HelpU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HelpU` DEFAULT CHARACTER SET utf8 ;
USE `Service` ;

-- -----------------------------------------------------
-- Table `Service`.`LOCALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`LOCALIDAD` (
  `Id_Localidad` INT NOT NULL,
  `NombreLocalidad` VARCHAR(45) NOT NULL,
  `Id_Provincia1` INT NOT NULL,
  PRIMARY KEY (`Id_Localidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`EMPRESA` (
  `ID_Empresa` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `ID_Localidad2` INT NOT NULL,
  PRIMARY KEY (`ID_Empresa`),
  INDEX `ID_Localidad2_idx` (`ID_Localidad2` ASC) VISIBLE,
  CONSTRAINT `ID_Localidad2`
    FOREIGN KEY (`ID_Localidad2`)
    REFERENCES `Service`.`LOCALIDAD` (`ID_Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`CLIENTE` (
  `Id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Id_Localidad1` INT NOT NULL,
  `CodigoPostal` INT NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`TIPO_EQUIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`TIPO_EQUIPO` (
  `ID_TipoEquipo` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_TipoEquipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`CLIENTE_POR_EQUIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`CLIENTE_POR_EQUIPO` (
  `ID_ClienteXequipo` INT NOT NULL,
  `ID_Cliente1` INT NOT NULL,
  `ID_Equipo2` INT NOT NULL,
  PRIMARY KEY (`ID_ClienteXequipo`),
  INDEX `ID_Cliente_idx` (`ID_Cliente1` ASC) VISIBLE,
  INDEX `ID_Equipo_idx` (`ID_Equipo2` ASC) VISIBLE,
  CONSTRAINT `ID_Cliente1`
    FOREIGN KEY (`ID_Cliente1`)
    REFERENCES `Service`.`CLIENTE` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Equipo2`
    FOREIGN KEY (`ID_Equipo2`)
    REFERENCES `Service`.`EQUIPO` (`ID_Equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`EQUIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`EQUIPO` (
  `ID_Equipo` INT NOT NULL,
  `Serial` INT NOT NULL,
  `ID_TipoEquipo` INT NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `AnoFab` YEAR NOT NULL,
  `FechaAlta` DATE NOT NULL,
  `ID_ClienteXequipo1` INT NOT NULL,
  PRIMARY KEY (`ID_Equipo`, `Serial`),
  INDEX `ID_TipoEquipo_idx` (`ID_TipoEquipo` ASC) VISIBLE,
  INDEX `ID_ClienteXequipo1_idx` (`ID_ClienteXequipo1` ASC) VISIBLE,
  CONSTRAINT `ID_TipoEquipo`
    FOREIGN KEY (`ID_TipoEquipo`)
    REFERENCES `Service`.`TIPO_EQUIPO` (`ID_TipoEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_ClienteXequipo1`
    FOREIGN KEY (`ID_ClienteXequipo1`)
    REFERENCES `Service`.`CLIENTE_POR_EQUIPO` (`ID_ClienteXequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`ORDEN_TRABAJO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`ORDEN_TRABAJO` (
  `ID_Orden` INT NOT NULL,
  `ID_Tecnico` INT NOT NULL,
  `EstadoOrden` TINYINT NOT NULL,
  `Fecha` DATE NOT NULL,
  `ID_Cliente2` INT NOT NULL,
  PRIMARY KEY (`ID_Orden`, `ID_Tecnico`),
  INDEX `ID_Cliente_idx` (`ID_Cliente2` ASC) VISIBLE,
  CONSTRAINT `ID_Cliente2`
    FOREIGN KEY (`ID_Cliente2`)
    REFERENCES `Service`.`CLIENTE` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`SERVICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`SERVICIO` (
  `ID_Servicio` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Precio` DECIMAL NOT NULL,
  PRIMARY KEY (`ID_Servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`SERVICIO_POR_ORDEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`SERVICIO_POR_ORDEN` (
  `ID_ServicioOrden` INT NOT NULL,
  `ID_Orden1` INT NOT NULL,
  `ID_Servicio1` INT NOT NULL,
  `ID_Equipo1` INT NOT NULL,
  PRIMARY KEY (`ID_ServicioOrden`),
  INDEX `ID_Orden_idx` (`ID_Orden1` ASC) VISIBLE,
  INDEX `ID_Equipo_idx` (`ID_Equipo1` ASC) VISIBLE,
  INDEX `ID_Servicio_idx` (`ID_Servicio1` ASC) VISIBLE,
  CONSTRAINT `ID_Orden1`
    FOREIGN KEY (`ID_Orden1`)
    REFERENCES `Service`.`ORDEN_TRABAJO` (`ID_Orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Servicio1`
    FOREIGN KEY (`ID_Servicio1`)
    REFERENCES `Service`.`SERVICIO` (`ID_Servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Equipo1`
    FOREIGN KEY (`ID_Equipo1`)
    REFERENCES `Service`.`EQUIPO` (`ID_Equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`FACTURA` (
  `ID_Factura` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `FormaPago` VARCHAR(45) NOT NULL,
  `TipoFactura` VARCHAR(45) NOT NULL,
  `ID_Cliente3` INT NOT NULL,
  PRIMARY KEY (`ID_Factura`),
  INDEX `ID_Cliente_idx` (`ID_Cliente3` ASC) VISIBLE,
  CONSTRAINT `ID_Cliente3`
    FOREIGN KEY (`ID_Cliente3`)
    REFERENCES `Service`.`CLIENTE` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`DETALLE_FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`DETALLE_FACTURA` (
  `ID_Item` INT NOT NULL,
  `ID_Orden2` INT NOT NULL,
  `ID_Factura1` INT NOT NULL,
  `ID_ServicioOrden1` INT NOT NULL,
  PRIMARY KEY (`ID_Item`),
  INDEX `ID_Orden_idx` (`ID_Orden2` ASC) VISIBLE,
  INDEX `ID_Factura_idx` (`ID_Factura1` ASC) VISIBLE,
  CONSTRAINT `ID_Orden2`
    FOREIGN KEY (`ID_Orden2`)
    REFERENCES `Service`.`ORDEN_TRABAJO` (`ID_Orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Factura1`
    FOREIGN KEY (`ID_Factura1`)
    REFERENCES `Service`.`FACTURA` (`ID_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_ServicioOrden1`
    FOREIGN KEY (`ID_ServicioOrden1`)
    REFERENCES `Service`.`SERVICIO_POR_ORDEN` (`ID_ServicioOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`CLIENTE` (
  `Id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Id_Localidad1` INT NOT NULL,
  `CodigoPostal` INT NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`LOCALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`LOCALIDAD` (
  `Id_Localidad` INT NOT NULL,
  `NombreLocalidad` VARCHAR(45) NOT NULL,
  `Id_Provincia1` INT NOT NULL,
  PRIMARY KEY (`Id_Localidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`PROVINCIA` (
  `Id_Provincia` INT NOT NULL,
  `NombreProvincia` VARCHAR(45) NOT NULL,
  `Id_Pais` INT NOT NULL,
  PRIMARY KEY (`Id_Provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`PAIS` (
  `Id_Pais` INT NOT NULL,
  `NombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Pais`))
ENGINE = InnoDB;

USE `HelpU` ;

-- -----------------------------------------------------
-- Table `HelpU`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`PAIS` (
  `Id_Pais` INT NOT NULL,
  `NombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`PROVINCIA` (
  `Id_Provincia` INT NOT NULL,
  `NombreProvincia` VARCHAR(45) NOT NULL,
  `Id_Pais1` INT NOT NULL,
  PRIMARY KEY (`Id_Provincia`),
  INDEX `Id_Pais_idx` (`Id_Pais1` ASC) VISIBLE,
  CONSTRAINT `Id_Pais1`
    FOREIGN KEY (`Id_Pais1`)
    REFERENCES `HelpU`.`PAIS` (`Id_Pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`LOCALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`LOCALIDAD` (
  `Id_Localidad` INT NOT NULL,
  `NombreLocalidad` VARCHAR(45) NOT NULL,
  `Id_Provincia1` INT NOT NULL,
  PRIMARY KEY (`Id_Localidad`),
  INDEX `Id_Provincia1_idx` (`Id_Provincia1` ASC) VISIBLE,
  CONSTRAINT `Id_Provincia1`
    FOREIGN KEY (`Id_Provincia1`)
    REFERENCES `HelpU`.`PROVINCIA` (`Id_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`TIPO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`TIPO_USUARIO` (
  `Id_TipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `TipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_TipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`USUARIO` (
  `Id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Contraseña` VARCHAR(8) NOT NULL,
  `Id_TipoUsuario1` INT NOT NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `FechaAlta` DATE NOT NULL,
  `FechaUltimaModificacion` DATE NOT NULL,
  PRIMARY KEY (`Id_Usuario`, `Contraseña`),
  INDEX `Id_TipoUsuario_idx` (`Id_TipoUsuario1` ASC) VISIBLE,
  CONSTRAINT `Id_TipoUsuario1`
    FOREIGN KEY (`Id_TipoUsuario1`)
    REFERENCES `HelpU`.`TIPO_USUARIO` (`Id_TipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`CLIENTE` (
  `Id_Cliente` INT NOT NULL,
  `Id_Usuario1` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Id_Localidad1` INT NOT NULL,
  `CodigoPostal` INT NOT NULL,
  `E-Mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Cliente`),
  INDEX `Id_Localidad1_idx` (`Id_Localidad1` ASC) VISIBLE,
  INDEX `Id_Usuario_idx` (`Id_Usuario1` ASC) VISIBLE,
  CONSTRAINT `Id_Localidad1`
    FOREIGN KEY (`Id_Localidad1`)
    REFERENCES `HelpU`.`LOCALIDAD` (`Id_Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Usuario1`
    FOREIGN KEY (`Id_Usuario1`)
    REFERENCES `HelpU`.`USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`CONTACTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`CONTACTO` (
  `Id_Contacto` INT NOT NULL AUTO_INCREMENT,
  `E-Mail` VARCHAR(45) NOT NULL,
  `FechaContacto` DATE NOT NULL,
  `Mensaje` VARCHAR(200) NOT NULL,
  `Id_Cliente2` INT NOT NULL,
  PRIMARY KEY (`Id_Contacto`),
  INDEX `Id_Cliente2_idx` (`Id_Cliente2` ASC) VISIBLE,
  CONSTRAINT `Id_Cliente2`
    FOREIGN KEY (`Id_Cliente2`)
    REFERENCES `HelpU`.`CLIENTE` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`HISTORICO_CAMBIO_PASS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`HISTORICO_CAMBIO_PASS` (
  `Id_Cliente3` INT NOT NULL,
  `Id_Usuario2` INT NOT NULL,
  `FechaSolicitud` DATE NOT NULL,
  `FechaExpiracion` DATE NULL,
  INDEX `Id_Cliente3_idx` (`Id_Cliente3` ASC) VISIBLE,
  INDEX `Id_Usuario2_idx` (`Id_Usuario2` ASC) VISIBLE,
  CONSTRAINT `Id_Cliente3`
    FOREIGN KEY (`Id_Cliente3`)
    REFERENCES `HelpU`.`CLIENTE` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Usuario2`
    FOREIGN KEY (`Id_Usuario2`)
    REFERENCES `HelpU`.`USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
