-- MySQL Script generated by MySQL Workbench
-- Mon Nov  1 19:39:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HelpU
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HelpU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HelpU` DEFAULT CHARACTER SET utf8 ;
USE `HelpU` ;

-- -----------------------------------------------------
-- Table `HelpU`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`PAIS` (
  `Id_Pais` INT NOT NULL,
  `NombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`PROVINCIA` (
  `Id_Provincia` INT NOT NULL,
  `NombreProvincia` VARCHAR(45) NOT NULL,
  `Id_Pais1` INT NOT NULL,
  PRIMARY KEY (`Id_Provincia`),
  INDEX `Id_Pais_idx` (`Id_Pais1` ASC),
  CONSTRAINT `Id_Pais1`
    FOREIGN KEY (`Id_Pais1`)
    REFERENCES `HelpU`.`PAIS` (`Id_Pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`LOCALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`LOCALIDAD` (
  `Id_Localidad` INT NOT NULL,
  `NombreLocalidad` VARCHAR(45) NOT NULL,
  `Id_Provincia1` INT NOT NULL,
  PRIMARY KEY (`Id_Localidad`),
  INDEX `Id_Provincia1_idx` (`Id_Provincia1` ASC),
  CONSTRAINT `Id_Provincia1`
    FOREIGN KEY (`Id_Provincia1`)
    REFERENCES `HelpU`.`PROVINCIA` (`Id_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`TIPO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`TIPO_USUARIO` (
  `Id_TipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `TipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_TipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`USUARIO` (
  `Id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Contraseña` VARCHAR(8) NOT NULL,
  `Id_TipoUsuario1` INT NOT NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `FechaAlta` DATE NOT NULL,
  `FechaUltimaModificacion` DATE NOT NULL,
  PRIMARY KEY (`Id_Usuario`, `Contraseña`),
  INDEX `Id_TipoUsuario_idx` (`Id_TipoUsuario1` ASC),
  CONSTRAINT `Id_TipoUsuario1`
    FOREIGN KEY (`Id_TipoUsuario1`)
    REFERENCES `HelpU`.`TIPO_USUARIO` (`Id_TipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`CLIENTE` (
  `Id_Cliente` INT NOT NULL,
  `Id_Usuario1` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Id_Localidad1` INT NOT NULL,
  `CodigoPostal` INT NOT NULL,
  `EMail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Cliente`),
  INDEX `Id_Localidad1_idx` (`Id_Localidad1` ASC),
  INDEX `Id_Usuario_idx` (`Id_Usuario1` ASC),
  CONSTRAINT `Id_Localidad1`
    FOREIGN KEY (`Id_Localidad1`)
    REFERENCES `HelpU`.`LOCALIDAD` (`Id_Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Usuario1`
    FOREIGN KEY (`Id_Usuario1`)
    REFERENCES `HelpU`.`USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`CONTACTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`CONTACTO` (
  `Id_Contacto` INT NOT NULL AUTO_INCREMENT,
  `E-Mail` VARCHAR(45) NOT NULL,
  `FechaContacto` DATE NOT NULL,
  `Mensaje` VARCHAR(200) NOT NULL,
  `Id_Cliente2` INT NULL,
  PRIMARY KEY (`Id_Contacto`),
  INDEX `Id_Cliente2_idx` (`Id_Cliente2` ASC),
  CONSTRAINT `Id_Cliente2`
    FOREIGN KEY (`Id_Cliente2`)
    REFERENCES `HelpU`.`CLIENTE` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`HISTORICO_CAMBIO_PASS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`HISTORICO_CAMBIO_PASS` (
  `Id_Cliente3` INT NOT NULL,
  `Id_Usuario2` INT NOT NULL,
  `FechaSolicitud` DATE NOT NULL,
  `FechaExpiracion` DATE NULL,
  INDEX `Id_Cliente3_idx` (`Id_Cliente3` ASC),
  INDEX `Id_Usuario2_idx` (`Id_Usuario2` ASC),
  CONSTRAINT `Id_Cliente3`
    FOREIGN KEY (`Id_Cliente3`)
    REFERENCES `HelpU`.`CLIENTE` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Usuario2`
    FOREIGN KEY (`Id_Usuario2`)
    REFERENCES `HelpU`.`USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;