-- MySQL Script generated by MySQL Workbench
-- Mon Nov  1 19:39:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HelpU
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HelpU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HelpU` DEFAULT CHARACTER SET utf8 ;
USE `HelpU` ;

-- -----------------------------------------------------
-- Table `HelpU`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`PAIS` (
  `Id_Pais` INT NOT NULL,
  `NombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`PROVINCIA` (
  `Id_Provincia` INT NOT NULL,
  `NombreProvincia` VARCHAR(45) NOT NULL,
  `Id_Pais1` INT NOT NULL,
  PRIMARY KEY (`Id_Provincia`),
  INDEX `Id_Pais_idx` (`Id_Pais1` ASC),
  CONSTRAINT `Id_Pais1`
    FOREIGN KEY (`Id_Pais1`)
    REFERENCES `HelpU`.`PAIS` (`Id_Pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`LOCALIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`LOCALIDAD` (
  `Id_Localidad` INT NOT NULL,
  `NombreLocalidad` VARCHAR(45) NOT NULL,
  `Id_Provincia1` INT NOT NULL,
  PRIMARY KEY (`Id_Localidad`),
  INDEX `Id_Provincia1_idx` (`Id_Provincia1` ASC),
  CONSTRAINT `Id_Provincia1`
    FOREIGN KEY (`Id_Provincia1`)
    REFERENCES `HelpU`.`PROVINCIA` (`Id_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`TIPO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`TIPO_USUARIO` (
  `Id_TipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `TipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_TipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`USUARIO` (
  `Id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Contraseña` VARCHAR(8) NOT NULL,
  `Id_TipoUsuario1` INT NOT NULL,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `FechaAlta` DATE NOT NULL,
  `FechaUltimaModificacion` DATE NOT NULL,
  PRIMARY KEY (`Id_Usuario`, `Contraseña`),
  INDEX `Id_TipoUsuario_idx` (`Id_TipoUsuario1` ASC),
  CONSTRAINT `Id_TipoUsuario1`
    FOREIGN KEY (`Id_TipoUsuario1`)
    REFERENCES `HelpU`.`TIPO_USUARIO` (`Id_TipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`CLIENTE` (
  `Id_Cliente` INT NOT NULL,
  `Id_Usuario1` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Id_Localidad1` INT NOT NULL,
  `CodigoPostal` INT NOT NULL,
  `EMail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Cliente`),
  INDEX `Id_Localidad1_idx` (`Id_Localidad1` ASC),
  INDEX `Id_Usuario_idx` (`Id_Usuario1` ASC),
  CONSTRAINT `Id_Localidad1`
    FOREIGN KEY (`Id_Localidad1`)
    REFERENCES `HelpU`.`LOCALIDAD` (`Id_Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Usuario1`
    FOREIGN KEY (`Id_Usuario1`)
    REFERENCES `HelpU`.`USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`CONTACTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`CONTACTO` (
  `Id_Contacto` INT NOT NULL AUTO_INCREMENT,
  `E-Mail` VARCHAR(45) NOT NULL,
  `FechaContacto` DATE NOT NULL,
  `Mensaje` VARCHAR(200) NOT NULL,
  `Id_Cliente2` INT NULL,
  PRIMARY KEY (`Id_Contacto`),
  INDEX `Id_Cliente2_idx` (`Id_Cliente2` ASC),
  CONSTRAINT `Id_Cliente2`
    FOREIGN KEY (`Id_Cliente2`)
    REFERENCES `HelpU`.`CLIENTE` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HelpU`.`HISTORICO_CAMBIO_PASS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HelpU`.`HISTORICO_CAMBIO_PASS` (
  `Id_Cliente3` INT NOT NULL,
  `Id_Usuario2` INT NOT NULL,
  `FechaSolicitud` DATE NOT NULL,
  `FechaExpiracion` DATE NULL,
  INDEX `Id_Cliente3_idx` (`Id_Cliente3` ASC),
  INDEX `Id_Usuario2_idx` (`Id_Usuario2` ASC),
  CONSTRAINT `Id_Cliente3`
    FOREIGN KEY (`Id_Cliente3`)
    REFERENCES `HelpU`.`CLIENTE` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Usuario2`
    FOREIGN KEY (`Id_Usuario2`)
    REFERENCES `HelpU`.`USUARIO` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/*Se añaden datos necesarios para realizar registro de usuario en la base de datos*/
INSERT into TIPO_USUARIO(TipoUsuario) VALUE ('admin');
INSERT into TIPO_USUARIO(TipoUsuario) VALUE ('cliente');

/*a. Registrar un nuevo usuario a la base de datos.*/
INSERT into USUARIO(Contraseña,id_TipoUsuario1,NombreUsuario,FechaAlta,FechaUltimaModificacion)
VALUES ('123456',2,'Juan',CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

/*b. Consultar si existe el usuario “Juan” en la base de datos y si la contraseña “123456” es
correcta.*/
SELECT NombreUsuario,Contraseña FROM usuario WHERE NombreUsuario='Juan' and Contraseña='123456';

/*Se añaden 3 datos importantes para realizar la consigna c*/
INSERT into PAIS(Id_Pais,NombrePais) VALUE (1,'Argentina');
INSERT into PROVINCIA(Id_Pais1,Id_Provincia,NombreProvincia) VALUE (1,1,'Córdoba');
INSERT into LOCALIDAD(Id_Provincia1,Id_Localidad,NombreLocalidad) VALUE (1,1,'Córdoba Capital');

/*c. Insertar un registro en nuestra entidad principal.*/
INSERT into CLIENTE(id_Cliente,id_Usuario1,Nombre,Apellido,FechaNacimiento,Id_Localidad1,Direccion,CodigoPostal,Email) 
VALUES (1,1,'Juan','Doe',19980422,1,'Bv Illia 300',5000,'test@gmail.com');

/*d. Actualizar un dato en nuestra entidad principal para un registro específico*/
UPDATE CLIENTE SET Direccion='Bv Illia 500' WHERE Id_Cliente=1;

/*Se añade otra localidad para realizar modificaciones mas adelante*/
INSERT into LOCALIDAD(Id_Provincia1,Id_Localidad,NombreLocalidad) VALUE (1,2,'Colón');

/*e. Actualizar un dato en nuestra entidad principal para un grupo de registros.*/
UPDATE CLIENTE SET Direccion='Av Goycoechea 300',id_Localidad1=2, CodigoPostal=5105  WHERE Id_Cliente=1;

/*Se inserta un nuevo usuario que va a ser eliminado*/
INSERT into USUARIO(Contraseña,id_TipoUsuario1,NombreUsuario,FechaAlta,FechaUltimaModificacion)
VALUES ('123',2,'Pablo',CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

/*f. Eliminar un registro específico de la base de datos.*/
DELETE FROM USUARIO WHERE NombreUsuario='Pablo';
